remote_theme: pages-themes/primer@v0.1.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Zahir Editions
description: Zahir Editions are a easy-to-use, online bookstore that lets you read ebooks without a network or browser difference.